<template>
  <div>
    <table border="1"
      bordercolor="#e8e8e8">
      <tbody>
        <tr>
          <td>委员会</td>
          <td>工作语言</td>
          <td>议题</td>
          <td>代表团制</td>
          <td>国家数量</td>
        </tr>
        <tr>
          <td>大使项目</td>
          <td>英文</td>
          <td>联合国多边主义的合作与实践</td>
          <td>双代</td>
          <td>20</td>
        </tr>
        <tr>
          <td>联合国大会第四委员会</td>
          <td>英文</td>
          <td>联合国维和任务的效率评估</td>
          <td>双代</td>
          <td>50</td>
        </tr>
      </tbody>
    </table>
    <div>
      注：2019年北京大学学生模拟联合国校际交流会将采用“北京大学标准议事规则”。大使项目、主新闻中心的议事规则有别于标准议事规则，将在后续发布。
    </div>
  </div>
</template>
